spring:
  application:
    name: Xboot-zuul

  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:  #zuul配置
  routes:  #路由
    api-a:  #api-a 名称可自取
      path: /api/a/**  #路径,*代表全目录匹配
      serviceId:    #需要聚合服务的name
    api-b:
      path: /api/b/**
      serviceId: